repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # last version to support py36
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: pretty-format-json
        args: [ --autofix ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/qiaouchicago/markdown-toc
    rev: 0.1.0
    hooks:
      - id: markdown-toc
